name: Manual Clean Up
on:
 workflow_dispatch:

jobs:
 destroy-infrastructure:
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
   steps:
     - name: Checkout
       uses: actions/checkout@v3
      
     - name: Show Destroy plan
       run: terraform plan -destroy -out=destroy.tfplan 
       continue-on-error: true

     - name: Terraform destroy
       id: destroy
       run: terraform destroy -auto-approve