name: "Manual Clean Up"

defaults:
  run:
    working-directory: infra/

on:
 workflow_dispatch:
   inputs:
      environment:
        required: true
        type: string
      deployment:
        required: false
        default: false
        type: boolean

   secrets:
      WORKSPACE_BASE:
        required: true
      AWS_ACCESS_KEY_ID:
        required: false
      AWS_SECRET_ACCESS_KEY:
        required: false
      TF_API_TOKEN:
        required: true
      CI_GITHUB_TOKEN:
        required: false
      

jobs:
 destroy-infrastructure:
   runs-on: ubuntu-latest
   env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_WORKSPACE: ${{ secrets.WORKSPACE_BASE }}-${{ inputs.environment }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      WORKSPACE_BASE: ${{ secrets.WORKSPACE_BASE }}
      AWS_REGION: 'us-west-1'
   steps:
     - name: Checkout
       uses: actions/checkout@v3
     
     - name: Setup Terraform
       uses: hashicorp/setup-terraform@v1

     - name: Display structure of downloaded files
        run: ls -R

     - name: Terraform Init
       id: init
       run: terraform init 
      
     - name: Show Destroy plan
       run: terraform plan -destroy -out=destroy.tfplan 
       continue-on-error: true

     - name: Terraform destroy
       id: destroy
       run: terraform destroy -auto-approve